apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adoption-journey-dev
commonLabels:
  variant: dev

resources:
  - ../base

images:
  - name: cartservice
    newName: registry.digitalocean.com/adoption-journey/cartservice
    newTag: v1.0.0
  - name: checkoutservice
    newName: registry.digitalocean.com/adoption-journey/checkoutservice
    newTag: v1.0.0
  - name: currencyservice
    newName: registry.digitalocean.com/adoption-journey/currencyservice
    newTag: v1.0.0
  - name: emailservice
    newName: registry.digitalocean.com/adoption-journey/emailservice
    newTag: v1.0.0
  - name: frontend
    newName: registry.digitalocean.com/adoption-journey/frontend
    newTag: v1.0.0
  - name: paymentservice
    newName: registry.digitalocean.com/adoption-journey/paymentservice
    newTag: v1.0.0
  - name: productcatalogservice
    newName: registry.digitalocean.com/adoption-journey/productcatalogservice
    newTag: v1.0.0
  - name: recommendationservice
    newName: registry.digitalocean.com/adoption-journey/recommendationservice
    newTag: v1.0.0
  - name: shippingservice
    newName: registry.digitalocean.com/adoption-journey/shippingservice
    newTag: v1.0.0
